name: "Release"

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: 'PyPi Release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Infastructure'
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Twine
        run: |
          pip install twine
      - name: Build and Distribute
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist
          twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
