name: "Tests"

on:
  push:
    branches:
      - master

jobs:
  test-general:
    name: 'Test Package'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Ibis_MSSQL_2017
    steps:
      - name: 'Checkout Infastructure'
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ODBC Drivers
        run: |
          sudo ci/scripts/install-mssql-odbc.sh
      - name: Install ibis_mssql
        run: |
          pip install .[develop]
      - name: Black Formatting
        run: |
          black --check ibis_mssql
      - name: Flake8 Checks
        run: |
          flake8
      - name: Upload Data to MSSQL Database
        run: |
          python ci/scripts/datamgr.py download
          python ci/scripts/datamgr.py mssql
      - name: Tests
        run: |
          pytest
